function  cards3j  = shufflecards3j()
%This function returns a shuffled deck of card with 3 jokers.
%The function returns a struct that contains two attributes: name and value
%The joker-value is set to 0.
%
%Example of use:
%cards3j  = shufflecards3j()
%cards3j(1).name
%cards3j(1).value

%assign value to each card
card3j_values=[1:10,10,10,10,1:10,10,10,10,1:10,10,10,10,1:10,10,10,10,0,0,0]';
card3j_name=['Ace of Hearts   ';'Two of Hearts   ';'Three of Hearts ';...
    'Four of Hearts  ';'Five of Hearts  ';'Six of Hearts   ';'Seven of Hearts ';...
    'Eight of Hearts ';'Nine of Hearts  ';'Ten of Hearts   ';...
    'Knave of Hearts ';'Queen of Hearts ';'King of Hearts  ';...
    'Ace of Tiles    ';'Two of Tiles    ';'Three of Tiles  ';...
    'Four of Tiles   ';'Five of Tiles   ';'Six of Tiles    ';'Seven of Tiles  ';...
    'Eight of Tiles  ';'Nine of Tiles   ';'Ten of Tiles    ';...
    'Knave of Tiles  ';'Queen of Tiles  ';'King of Tiles   ';...
    'Ace of Clovers  ';'Two of Clovers  ';'Three of Clovers';...
    'Four of Clovers ';'Five of Clovers ';'Six of Clovers  ';'Seven of Clovers';...
    'Eight of Clovers';'Nine of Clovers ';'Ten of Clovers  ';...
    'Knave of Clovers';'Queen of Clovers';'King of Clovers ';...
    'Ace of Pikes    ';'Two of Pikes    ';'Three of Pikes  ';...
    'Four of Pikes   ';'Five of Pikes   ';'Six of Pikes    ';'Seven of Pikes  ';...
    'Eight of Pikes  ';'Nine of Pikes   ';'Ten of Pikes    ';...
    'Knave of Pikes  ';'Queen of Pikes  ';'King of Pikes   ';...
    'Joker1          ';'Joker2          ';'Joker3          '
    ];
ranks = {'Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Knave','Queen','King', ...
         'Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Knave','Queen','King', ...
         'Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Knave','Queen','King', ...
         'Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Knave','Queen','King', ...
         'Joker','Joker','Joker'};
suits = {'Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts','Hearts', ...
         'Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles','Tiles', ...
         'Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers','Clovers', ...
         'Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes','Pikes', ...
         'Joker','Joker','Joker'};

Card3j_index=randperm(55);%makes random shuffled index list of cards

for n=1:length(Card3j_index)
    cards3j(n).name=card3j_name(Card3j_index(n),:);
    cards3j(n).suit=suits{Card3j_index(n)};
    cards3j(n).rank=ranks{Card3j_index(n)};
    cards3j(n).value=card3j_values(Card3j_index(n));
end